# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccurateBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('stake', models.IntegerField()),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accurate_bet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='New', max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('currency_pair', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=30)),
                ('total_users', models.IntegerField(default=0)),
                ('total_sum', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_sum', models.IntegerField(default=0)),
                ('sum_from', models.IntegerField()),
                ('sum_to', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Parley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('koefficient', models.FloatField()),
                ('min_sum', models.IntegerField()),
                ('max_sum', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('bet_sum', models.IntegerField(null=True)),
                ('bettor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parley_bettor', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parley_creator', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parleys', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=500)),
                ('sum', models.IntegerField(default=0)),
                ('bets', models.IntegerField(default=0)),
                ('events', models.IntegerField(default=0)),
                ('activity_rate', models.IntegerField(blank=True, null=True)),
                ('win_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_option', to='api.Option'),
        ),
        migrations.AddField(
            model_name='accuratebet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accurate_bet_event', to='api.Event'),
        ),
    ]
