# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
