# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parley',
            name='bettor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parley_bettor', to=settings.AUTH_USER_MODEL),
        ),
    ]
