# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180308_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='win_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
